### ISSUE TITLE
Call to undefined method Nette\Database\Drivers\MySqlDriver::formatBool()

### ISSUE THREAD

**Issue by prog** [nextras/migrations#101]
```php
$controller = new ConsoleController(
  new MySqlDriver(
    new NetteAdapter(
      new Nette\Database\Connection(...)
    )
  )
);
$controller->addGroup(...)
$controller->addExtension(...)
$controller->run();
```

```
Nextras Migrations
RESET
1 migration needs to be executed.
Nette\MemberAccessException: Call to undefined method Nette\Database\Drivers\MySqlDriver::formatBool(). in /app/vendor/nette/utils/src/Utils/ObjectHelpers.php:65
Stack trace:
#0 /app/vendor/nette/utils/src/Utils/SmartObject.php(42): Nette\Utils\ObjectHelpers::strictCall('Nette\\Database\\...', 'formatBool')
#1 /app/vendor/nextras/migrations/src/Bridges/NetteDatabase/NetteAdapter.php(59): Nette\Database\Drivers\MySqlDriver->__call('formatBool', Array)
#2 /app/vendor/nextras/migrations/src/Drivers/MySqlDriver.php(108): Nextras\Migrations\Bridges\NetteDatabase\NetteAdapter->escapeBool(false)
#3 /app/vendor/nextras/migrations/src/Engine/Runner.php(171): Nextras\Migrations\Drivers\MySqlDriver->insertMigration(Object(Nextras\Migrations\Entities\Migration))
#4 /app/vendor/nextras/migrations/src/Engine/Runner.php(127): Nextras\Migrations\Engine\Runner->execute(Object(Nextras\Migrations\Entities\File))
#5 /app/vendor/nextras/migrations/src/Controllers/ConsoleController.php(23): Nextras\Migrations\Engine\Runner->run('reset')
#6 /app/bin/db-migrate(13): Nextras\Migrations\Controllers\ConsoleController->run()
...
```

- nextras/migrations:v3.1.0-rc5
- nette/database:v3.0.1

https://github.com/nette/database/releases/tag/v3.0.0
> removed unused ISupplementalDriver::formatBool()

**Comment by JanTvrdik** [comment]
should be fixed in [3.1.0](https://github.com/nextras/migrations/releases/tag/v3.1.0)
